version: "3.8"

services:
  # Backend - PDF processing engine
  stirling-backend:
    image: stirlingtools/stirling-pdf:latest
    networks:
      - stirling
    environment:
      MODE: "BACKEND"
    volumes:
      - stirling-tessdata:/usr/share/tessdata
      - stirling-configs:/configs
      - stirling-logs:/logs
      - stirling-pipeline:/pipeline
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == polaris
      restart_policy:
        condition: on-failure

  # Frontend - Web interface (exposed via Traefik)
  stirling-frontend:
    image: stirlingtools/stirling-pdf:latest
    networks:
      - stirling
      - traefik-public
    environment:
      MODE: "FRONTEND"
      VITE_API_BASE_URL: "http://stirling-backend:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == polaris
      labels:
        - traefik.enable=true
        - traefik.http.routers.stirling.rule=Host(`stirling.kluhan.dev`) || Host(`pdf.kluhan.dev`)
        - traefik.http.routers.stirling.entrypoints=websecure
        - traefik.http.routers.stirling.tls=true
        - traefik.http.routers.stirling.tls.certresolver=letsencrypt
        - traefik.http.services.stirling.loadbalancer.server.port=8080
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
  stirling:
    driver: overlay
    attachable: true

volumes:
  stirling-tessdata:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.75,nfsvers=4,rw,noatime
      device: ":/mnt/aegis/docker-volumes/stirling-pdf/tessdata"

  stirling-configs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.75,nfsvers=4,rw,noatime
      device: ":/mnt/aegis/docker-volumes/stirling-pdf/configs"

  stirling-logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.75,nfsvers=4,rw,noatime
      device: ":/mnt/aegis/docker-volumes/stirling-pdf/logs"

  stirling-pipeline:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.75,nfsvers=4,rw,noatime
      device: ":/mnt/aegis/docker-volumes/stirling-pdf/pipeline"