version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    networks:
      - traefik-public
      - immich
    environment:
      # Core
      TZ: "Europe/Berlin"

      # Immich expects these
      REDIS_HOSTNAME: redis
      DB_HOSTNAME: database
      DB_PORT: "5432"
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD_FILE: /run/secrets/immich_db_password

      # Optional: if you later add public URL features
      # IMMICH_PUBLIC_LOGIN_PAGE_MESSAGE: "Homelab"

    volumes:
      - immich-uploads:/data
      - /etc/localtime:/etc/localtime:ro

    secrets:
      - immich_db_password

    deploy:
     replicas: 1
     placement:
       constraints:
         - node.hostname == polaris
      labels:
        - traefik.enable=true
        - traefik.http.routers.immich.rule=Host(`immich.kluhan.dev`)
        - traefik.http.routers.immich.entrypoints=websecure
        - traefik.http.routers.immich.tls=true
        - traefik.http.routers.immich.tls.certresolver=letsencrypt
        - traefik.http.services.immich.loadbalancer.server.port=2283
      restart_policy:
        condition: on-failure

 immich-machine-learning:
   image: ghcr.io/immich-app/immich-machine-learning:release
   networks:
     - immich
   environment:
     TZ: "Europe/Berlin"
   volumes:
     - immich-model-cache:/cache
   deploy:
     replicas: 1
     placement:
       constraints:
         - node.hostname == vega
     restart_policy:
       condition: on-failure

  redis:
    image: docker.io/valkey/valkey:9
    networks:
      - immich
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    networks:
      - immich
    environment:
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/immich_db_password
      POSTGRES_INITDB_ARGS: "--data-checksums"
    secrets:
      - immich_db_password
    volumes:
      - immich-db:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # Strongly recommended to pin DB to one node explicitly:
          - node.hostname == polaris
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
  immich:
    driver: overlay
    attachable: true

secrets:
  immich_db_password:
    external: true

volumes:
  immich-uploads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.75,nfsvers=4,rw,noatime
      device: ":/mnt/aegis/docker-volumes/immich-uploads"

  immich-model-cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.100.75,nfsvers=4,rw,noatime
      device: ":/mnt/aegis/docker-volumes/immich-model-cache"

  immich-db:
